export const keyboardButtons = [
  { key: 'Q', value: 'Q' },
  { key: 'W', value: 'W' },
  { key: 'E', value: 'E' },
  { key: 'R', value: 'R' },
  { key: 'T', value: 'T' },
  { key: 'Y', value: 'Y' },
  { key: 'U', value: 'U' },
  { key: 'I', value: 'I' },
  { key: 'O', value: 'O' },
  { key: 'P', value: 'P' },
  { key: 'A', value: 'A' },
  { key: 'S', value: 'S' },
  { key: 'D', value: 'D' },
  { key: 'F', value: 'F' },
  { key: 'G', value: 'G' },
  { key: 'H', value: 'H' },
  { key: 'J', value: 'J' },
  { key: 'K', value: 'K' },
  { key: 'L', value: 'L' },
  { key: 'Z', value: 'Z' },
  { key: 'X', value: 'X' },
  { key: 'C', value: 'C' },
  { key: 'V', value: 'V' },
  { key: 'B', value: 'B' },
  { key: 'N', value: 'N' },
  { key: 'M', value: 'M' },
];

export const dataset = {
  animal: [
    'GOAT',
    'LION',
    'ELEPHANT',
    'DOG',
    'CAT',
    'HORSE',
    'LION',
    'BEAR',
    'SNAKE',
    'FOX',
    'KANGAROO',
    'RABBIT',
    'TIGER',
    'LEOPARD',
    'GOOSE',
    'FROG',
    'MONKEY',
    'SHEEP',
    'WHALE',
    'CHICKEN',
    'PANDA',
    'ZEBRA',
    'DONKEY',
    'LIZARD',
    'GORILLA',
    'RACOON',
    'TURTLE',
  ],
  city: [
    'PARIS',
    'LONDON',
    'KANPUR',
    'NEWDELHI',
    'NEWYORK',
    'BALI',
    'MUMBAI',
    'PUNE',
    'CHICAGO',
    'MILAN',
    'SYDNEY',
    'TOKYO',
    'BERLIN',
    'DUBLIN',
    'JAIPUR',
    'VENICE',
    'KYOTO',
    'ATHENS',
    'BUDAPEST',
    'BUSAN',
    'BEIJING',
    'ROME',
  ],
  country: [
    'INDIA',
    'CHINA',
    'USA',
    'CANADA',
    'PAKISTAN',
    'RUSSIA',
    'SPAIN',
    'ITALY',
    'FRANCE',
    'GERMANY',
    'TURKEY',
    'ENGLAND',
    'BRAZIL',
    'ARGENTINA',
    'GREECE',
    'ALBANIA',
    'AUSTRIA',
    'NORWAY',
    'OMAN',
    'BULGARIA',
    'QATAR',
  ],
  body_part: [
    'HAND',
    'LEG',
    'FEET',
    'HEAD',
    'LUNGS',
    'HEART',
    'THROAT',
    'EYE',
    'NOSE',
    'MOUTH',
    'NECK',
    'STOMACH',
    'ELBOW',
    'EAR',
    'SPINE',
    'KNEE',
    'FINGER',
    'LIPS',
    'CHEST',
    'WAIST',
    'ANKLE',
    'CHIN',
  ],
};
